#############################################################################################################
# Docker Environment Configuration
#############################################################################################################

# 项目配置: 名称、日志目录
project:
 name: sa-admin
 log-directory: /app/logs/${project.name}/${spring.profiles.active}

# 项目端口和url根路径
server:
 port: 8080
 servlet:
 context-path: /

# 环境
spring:
 profiles:
 active: docker
